# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Clay for Kids - 3D' do
    inhibit_all_warnings!
    pod 'AFNetworking', '~> 2.5'
    pod 'Google-Mobile-Ads-SDK', '~> 7.3'
end

