# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'fvlive_iosapp_infonam' do
pod 'FFmpeg', '~> 2.2'
pod 'AFNetworking', '~> 2.6'
end

target 'fvlive_iosapp_infonamTests' do

end

